[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=49.2.0", "wheel"]
build-backend = "setuptools.build_meta"

#[tool.check-manifest]
#ignore = ["docs/", "venv/", "tests/", ".pypirc"]